# -*- coding: utf-8 -*-
"""Job_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAcDE7535JlOEe250jmNwNhtS684NYfw
"""

!python --version

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Job_1_resource_world_population.csv")

#9. perform initial inspection
df.head()

df.info()

df.isnull().sum()

#10. mean, median, varinace, and standard deviation
stats = df.groupby("Continent")["2022 Population"].agg(
    mean="mean",
    median="median",
    variance="var",
    std_dev="std"
)

stats

df.columns

#11. calculate cumulative population
year_cols = [col for col in df.columns if "Population" in col]

df["Cumulative_Population"] = df[year_cols].sum(axis=1)
df[["Country/Territory", "Cumulative_Population"]].head()

df.columns

# 12. change the column names
new_columns = {}

for col in df.columns:
    if "Population" in col:
        new_columns[col] = col.split()[0]

df.rename(columns=new_columns, inplace=True)

# Result
df.columns

#13. save the cleanest dataset
df.to_csv("processed_data.csv", index=False)

#14. visualizing continent-wise population
plt.figure(figsize=(8,5))
sns.histplot(data=df, x="1970", hue="Continent", multiple="stack")
plt.title("Continent-wise Population Distribution in 1970")
plt.savefig('Continent-wise Population Distribution in 1970.png')
plt.show()

plt.figure(figsize=(10,5))   # increasing figure width
sns.histplot(
    data=df,
    x="1970",
    hue="Continent",
    multiple="stack",
    bins=20
)
plt.title("Continent-wise Population Distribution in 1970")
plt.savefig('Continent-wise Population Distribution in 1970_width.png')
plt.show()



plt.figure(figsize=(8,5))
sns.histplot(data=df, x="2022", hue="Continent", multiple="stack")
plt.title("Continent-wise Population Distribution in 2022")
plt.savefig('Continent-wise Population Distribution in 2022.png')
plt.show()

#15. statistical reasoning
timeline = df.groupby("Continent")[["1970", "1990", "2000", "2022"]].sum()

timeline.T.plot(figsize=(10,6))
plt.title("Continent-wise Population Growth Timeline")
plt.xlabel("Year")
plt.ylabel("Population")
plt.savefig('Continent-wise Population Growth Timeline.png')
plt.show()

#16. correlation
corr_matrix = df.select_dtypes(include=np.number).corr()
corr_matrix

#16. visualize
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.savefig('Correlation Matrix.png')
plt.show()