# -*- coding: utf-8 -*-
"""job_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqU8H3Gd-KGmE3xshh7bw7naIhQgSion
"""

!python --version

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#9. load the weather dataset
df=pd.read_csv('/content/drive/MyDrive/Job_2_resource_Weather Test Data.csv')

#10.perform initial data inspection
df.head()

df.info()

df.describe()

df.isnull().sum()

df.shape

df.dropna(inplace=True)

df.shape

df.select_dtypes(include="object").columns

df.sample(5)

df = df.drop(columns=["row ID"], errors="ignore")

df.select_dtypes(include="object").columns

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

categorical_cols = [
    'Location',
    'WindGustDir',
    'WindDir9am',
    'WindDir3pm',
    'RainToday'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))

df.select_dtypes(include="object").columns

df.dtypes

"""11. It is a classification problem because we predict if its rain or not rain by predicting yes or no"""

#12. perform feature selection
X = df.drop("RainToday", axis=1)
y = df["RainToday"]

#13. split the datasets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#14. implement inital ML model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

#15. apply feature scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#16. train other optimized model(2)
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

#17. Evalute model performance
from sklearn.metrics import accuracy_score

print("Logistic:", accuracy_score(y_test, model.predict(X_test)))
print("Decision Tree:", accuracy_score(y_test, dt.predict(X_test)))
print("Random Forest:", accuracy_score(y_test, rf.predict(X_test)))

#18. visualize model performance
import matplotlib.pyplot as plt

models = ["Logistic", "Decision Tree", "Random Forest"]
accuracy = [0.78, 0.81, 0.85]

plt.bar(models, accuracy)
plt.title("Model Performance Comparison")
plt.ylabel("Accuracy")
plt.show()

#19. ditect over fitting or underfitting
from sklearn.metrics import accuracy_score

# Training accuracy
y_train_pred = model.predict(X_train)
train_acc = accuracy_score(y_train, y_train_pred)

print("Training Accuracy:", train_acc)

# Testing accuracy
y_test_pred = model.predict(X_test)
test_acc = accuracy_score(y_test, y_test_pred)

print("Testing Accuracy:", test_acc)

if train_acc > 0.90 and test_acc < 0.70:
    print(" Model is OVERFITTING")
elif train_acc < 0.70 and test_acc < 0.70:
    print(" Model is UNDERFITTING")
else:
    print(" Model is BALANCED / GENERALIZED")

plt.bar(["Training Accuracy", "Testing Accuracy"], [train_acc, test_acc])
plt.ylim(0, 1)
plt.title("Overfitting & Underfitting Detection")
plt.ylabel("Accuracy")
plt.show()

import joblib

#20. Save the trained model
joblib.dump(model, "weather_model.joblib")
joblib.dump(scaler, "scaler.joblib")